// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDT-xHW4gDzSu9CRiT3I8TQnhcC5U8H4oM',
    appId: '1:782640777617:web:79722ff98aa741742d7230',
    messagingSenderId: '782640777617',
    projectId: 'sadiq-flutter',
    authDomain: 'sadiq-flutter.firebaseapp.com',
    databaseURL: 'https://sadiq-flutter-default-rtdb.firebaseio.com/',
    storageBucket: 'sadiq-flutter.appspot.com',
    measurementId: 'G-HY62YC5NGB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfjhQhsJh0XeN4dH2kQYWo-NyCF67cT9k',
    appId: '1:782640777617:android:1e09be97b3a7bc092d7230',
    messagingSenderId: '782640777617',
    projectId: 'sadiq-flutter',
    storageBucket: 'sadiq-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPbTR8YFN159VF95xbircjp-6qDJngGjs',
    appId: '1:782640777617:ios:3b87dc112bf4c4782d7230',
    messagingSenderId: '782640777617',
    projectId: 'sadiq-flutter',
    storageBucket: 'sadiq-flutter.appspot.com',
    iosClientId:
        '782640777617-8o5rrb322uovtlaj2fco902bokkcsbgq.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterTask2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPbTR8YFN159VF95xbircjp-6qDJngGjs',
    appId: '1:782640777617:ios:3b87dc112bf4c4782d7230',
    messagingSenderId: '782640777617',
    projectId: 'sadiq-flutter',
    storageBucket: 'sadiq-flutter.appspot.com',
    iosClientId:
        '782640777617-8o5rrb322uovtlaj2fco902bokkcsbgq.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterTask2',
  );
}
